version: "3.8"
services:
  postgres:
    image: "postgres:15.4-alpine3.18"
    hostname: postgre
    command:
      [
        "-c",
        "max_connections=2000",
        "-c",
        "effective_cache_size=25600MB",
        "-c",
        "work_mem=2MB",
        "-c",
        "wal_buffers=1MB",
        "-c",
        "synchronous_commit=off",
      ]
    volumes:
      - ~/.dockerdata/exchanger/postgre:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}